export const INVENTORY_STATUS = {
  UNLOADED: 'UNLOADED',
  STORED: 'STORED',
  INTRANSIT: 'INTRANSIT',
  TERMINATED: 'TERMINATED',
  TRANSFERED: 'TRANSFERED',
  DELETED: 'DELETED'
}

export const INVENTORY_TYPES = {
  BUFFER: 'BUFFER',
  SHELF: 'SHELF'
}
